name: Build and Check
on:
  pull_request:

permissions: {}

jobs:
  build-check:
    runs-on: ubuntu-latest
    name: Dependencies
    timeout-minutes: 15
    steps:
      - name: Checkout
        if: '!inputs.skip-checkout'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.11'
      - name: Install and configure Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: '1.4.0'
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install
      - name: Ruff format
        run: poetry run ruff format --check .
      - name: Ruff check
        run: poetry run ruff check .
        # TODO: Remove this when the configured checks are all passing.
        #       We added a bunch using a standard new project config!
        continue-on-error: true
      - name: Mypy
        run: poetry run mypy .
      - name: Pytest
        run: poetry run pytest .
